const questionPool = [
    {
        id: 1,
        text: "The most powerful ---- to parachuting is fear, but one should also take its high cost into account, as a total outfit for parachuting can be extremely expensive.",
        options: { 
            A: "resemblance", 
            B: "adjustment", 
            C: "deterrent", 
            D: "submission", 
            E: "adherence" 
        },
        correct: "C",
        category: "Kelime",
        subCategory: "İsimler (Nouns)",
        targetWord: "deterrent",
        explanation: "'Deterrent' caydırıcı unsur demektir. Cümlede 'paraşütle atlamaya karşı en güçlü caydırıcı unsur korkudur' denilmektedir. Diğer şıklar: resemblance (benzerlik), adjustment (ayarlama), submission (boyun eğme/teslimiyet), adherence (bağlılık/uyum)."
    },
    {
        id: 2,
        text: "Peanut may very well be the most common food allergy in some populations, but the ---- of a particular food allergy varies according to age and group.",
        options: { 
            A: "utilisation", 
            B: "withdrawal", 
            C: "precaution", 
            D: "termination", 
            E: "prevalence" 
        },
        correct: "E",
        category: "Kelime",
        subCategory: "İsimler (Nouns)",
        targetWord: "prevalence",
        explanation: "'Prevalence' yaygınlık, görülme sıklığı anlamına gelir. 'Belirli bir gıda alerjisinin yaygınlığı yaşa ve gruba göre değişir' anlamı çıkmaktadır. Diğer şıklar: utilisation (kullanım), withdrawal (geri çekilme/yoksunluk), precaution (önlem), termination (sonlandırma)."
    },
    {
        id: 3,
        text: "Since the mid-20th century, plastic pollution has increased ----, and the resulting pollution has become a global environmental issue.",
        options: { 
            A: "fluently", 
            B: "reluctantly", 
            C: "exponentially", 
            D: "mutually", 
            E: "deceptively" 
        },
        correct: "C",
        category: "Kelime",
        subCategory: "Zarflar (Adverbs)",
        targetWord: "exponentially",
        explanation: "'Exponentially' katlanarak, gittikçe hızlanan bir şekilde demektir. Plastik kirliliğinin katlanarak arttığı ifade ediliyor. Diğer şıklar: fluently (akıcı bir şekilde), reluctantly (gönülsüzce), mutually (karşılıklı olarak), deceptively (aldatıcı bir şekilde)."
    },
    {
        id: 4,
        text: "The Earth’s magnetic field is generated by the motion of molten iron in its core, which ---- a protective shield against harmful solar radiation.",
        options: { 
            A: "creates", 
            B: "disturbs", 
            C: "conceals", 
            D: "abandons", 
            E: "invades" 
        },
        correct: "A",
        category: "Kelime",
        subCategory: "Fiiller (Verbs)",
        targetWord: "create",
        explanation: "'Create' oluşturmak, yaratmak demektir. Dünyanın manyetik alanının zararlı güneş radyasyonuna karşı koruyucu bir kalkan 'oluşturduğu' anlatılmaktadır. Diğer şıklar: disturb (rahatsız etmek), conceal (gizlemek), abandon (terk etmek), invade (işgal etmek)."
    },
    {
        id: 5,
        text: "Many species of birds ---- long journeys twice a year, travelling thousands of miles between their breeding and wintering grounds.",
        options: { 
            A: "make up", 
            B: "turn down", 
            C: "put off", 
            D: "give in", 
            E: "set out on" 
        },
        correct: "E",
        category: "Kelime",
        subCategory: "Phrasal Verbs",
        targetWord: "set out on",
        explanation: "'Set out on' bir yolculuğa çıkmak/başlamak anlamına gelir. Kuşların yılda iki kez uzun yolculuklara çıktığı ifade edilmektedir. Diğer şıklar: make up (uydurmak/oluşturmak), turn down (reddetmek/kısmak), put off (ertelemek), give in (pes etmek)."
    },
    {
        id: 6,
        text: "By the time the rescue team finally ---- the stranded climbers, they ---- without food or water for over three days.",
        options: { 
            A: "reached / have been", 
            B: "had reached / were", 
            C: "reaches / will be", 
            D: "has reached / had been", 
            E: "reached / had been" 
        },
        correct: "E",
        category: "Gramer",
        subCategory: "Zamanlar (Tenses)",
        targetWord: "Past Simple / Past Perfect",
        explanation: "'By the time + Past Simple' yapısı, temel cümlede 'Past Perfect (had V3)' gerektirir. Kurtarma ekibi ulaştığında (reached), dağcılar çoktan üç gündür aç ve susuz kalmıştı (had been)."
    },
    {
        id: 7,
        text: "If the government ---- stricter regulations earlier, the current economic crisis ---- so severe.",
        options: { 
            A: "implemented / will not be", 
            B: "had implemented / would not be", 
            C: "implements / is not", 
            D: "has implemented / could not be", 
            E: "would implement / might not be" 
        },
        correct: "B",
        category: "Gramer",
        subCategory: "If Clauses (Mixed Type)",
        targetWord: "Mixed Conditionals",
        explanation: "Geçmişte yapılan bir eylemin (had implemented) şu andaki (current) sonucunu anlattığı için Mixed Type (Type 3 + Type 2) kullanılmalıdır: If + Past Perfect, would + V1."
    },
    {
        id: 8,
        text: "The transition ---- renewable energy sources is essential ---- reducing global carbon emissions.",
        options: { 
            A: "at / in", 
            B: "from / on", 
            C: "into / with", 
            D: "over / by", 
            E: "to / for" 
        },
        correct: "E",
        category: "Gramer",
        subCategory: "Edatlar (Prepositions)",
        targetWord: "transition to / essential for",
        explanation: "'Transition to' bir şeye geçiş yapmak demektir. 'Essential for' ise bir şey için gerekli/önemli anlamındadır. Yenilenebilir enerjiye (to) geçiş, emisyonları azaltmak için (for) gereklidir."
    },
    {
        id: 9,
        text: "---- the advancements in medical technology, certain diseases still remain a mystery to scientists.",
        options: { 
            A: "Despite", 
            B: "Because of", 
            C: "Similar to", 
            D: "Instead of", 
            E: "In addition to" 
        },
        correct: "A",
        category: "Gramer",
        subCategory: "Bağlaçlar (Conjunctions)",
        targetWord: "Despite",
        explanation: "Tıbbi teknolojideki ilerlemelere 'rağmen' (despite), bazı hastalıkların hala gizemini koruduğu belirtilerek zıtlık ilişkisi kurulmuştur. Arkasından isim öbeği aldığı için 'Despite' uygundur."
    },
    {
        id: 10,
        text: "Researchers suggest that ---- individuals sleep for at least seven hours a night, their cognitive functions will begin to decline over time.",
        options: { 
            A: "if", 
            B: "as long as", 
            C: "provided that", 
            D: "when", 
            E: "unless" 
        },
        correct: "E",
        category: "Gramer",
        subCategory: "Bağlaçlar (Conjunctions)",
        targetWord: "Unless",
        explanation: "'Unless' -medikçe/-madıkça (if not) anlamı katar. Kişiler gecede en az yedi saat uyumadıkça (unless), bilişsel işlevlerinin zamanla zayıflayacağı ifade edilmektedir."
    }
];
